services:
 mysqldb:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: p@ssw0rd
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
  command: --lower_case_table_names=1
  networks:
   - products-microservice-network
  ports:
   - "33306:3306"
  hostname: mysql-host-productsmicroservice

 products-microservice:
  image: productsmicroservice:1.0
  environment:
   SERVER: ${my_host}
   PORT: ${my_port}
   DATABASE: ${mysql__database}  
   UID: ${my_user}
   PASSWORD: ${mysql_pwd}   
  ports:
   - "8081:8080"
  networks:
   - products-microservice-network
  depends_on:
   - mysqldb

networks:
 products-microservice-network:
  driver: bridge