services:
 mysqldb:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: p@ssw0rd
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
  command: --lower_case_table_names=1
  networks:
   - products-microservice-network
  ports:
   - "3306:3306"
  hostname: mysql-host-productsmicroservice

 products-microservice:
  image: productsmicroservice:1.0.1
  environment:
   SERVER: localhost
   PORT: ${MYSQL_PORT}
   DATABASE: ${MYSQL_DB}   
   UID: ${MySQL_UID}
   PASSWORD: ${MYSQL_PASSWORD}
   MySQLDataConn: ${MySQL_Conn}
  ports:
   - "2026:2026"
  networks:
   - products-microservice-network
  depends_on:
   - mysqldb

networks:
 products-microservice-network:
  driver: bridge