services:
 mysqldb:
  image: mysql:8.4.3
  environment:
   MYSQL_ROOT_PASSWORD: p@ssw0rd
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
  command: --lower_case_table_names=1
  networks:
   - products-microservice-network
  ports:
   - "3306:3306"
  hostname: mysql-host-productsmicroservice

 products-microservice:
  image: productsmicroservices:1.2
  environment:
   MYSQL_HOST: ${mysql_host}
   MYSQL_DATABASE: ${mysql_db}
   MYSQL_PORT: ${mysql_port}  
   MYSQL_UID: ${mysql_user}
   MYSQL_PASSWORD: ${mysql_pwd}   
  ports:
   - "8081:8080"
  networks:
   - products-microservice-network
  depends_on:
   - mysqldb

networks:
 products-microservice-network:
  driver: bridge